### ISSUE TITLE
Cannot get PreauthenticatedRequest

### ISSUE THREAD

**Issue by pnbao** [retracedgmbh/node-oci-client#39]
<img width="682" alt="Screen Shot 2020-02-14 at 17 15 55" src="https://user-images.githubusercontent.com/11147999/74513337-b1a9e900-4f4d-11ea-9e81-03d2f43d9ded.png">
### Error screen
<img width="1289" alt="Screen Shot 2020-02-14 at 16 54 58" src="https://user-images.githubusercontent.com/11147999/74512043-bde07700-4f4a-11ea-9ff5-b4aae62e7d85.png">

I have setup the privateKey as the text of the PEM key and meet this error. 
Please tell me how to fix this.

**Comment by bangretraced** [comment]
sorry for the incorrect doc. You need base64 of your content PEM key
